version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_USER:  root
      DB_PASSWORD: 29/jSGGz&x0c
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: nobi_investment
    networks:
      - nobi_assesment 
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-29/jSGGz&x0c}
      MARIADB_DATABASE: ${MYSQL_DATABASE:-nobi_investment}
      MARIADB_USER: ${MYSQL_USER:-user}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD:-29/jSGGz&x0c}
      MARIADB_AUTO_UPGRADE: "true"
      MARIADB_INITDB_SKIP_TZINFO: "false"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nobi_assesment
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
    driver: local

networks:
  nobi_assesment:
    driver: bridge
